### ISSUE TITLE
error saat proses tokenize, dan langsung memutus koneksi dgn device (mode debug)

### ISSUE THREAD

**Issue by ifin2000** [salkuadrat/fxendit#1]
saya pakai mode test, 
berikut log yg ada di vscode :
I/flutter (20464): valid!
W/d.iconix.mobil(20464): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/d.iconix.mobil(20464): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/d.iconix.mobil(20464): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
D/OkHttp  (20464): --> POST https://logs.logdna.com/logs/ingest?hostname=xendit.co http/1.1
D/OkHttp  (20464): Content-Type: application/json;charset=UTF-8
D/OkHttp  (20464): Content-Length: 176
D/OkHttp  (20464): Authorization: Basic ZjMyNDg1NGZjYjJjYTNjMzk3YWEwNTM2ZTA1NTUwNzA6IA==
D/OkHttp  (20464): {"lines":[{"timestamp":1625192956,"line":"xnd_public_development_PYCFKOR10uCqkpQ6LOdPTDSTZdSioIV0wXLh\/Rhq\/WfS\/rCgDQF1 Start debugging","file":"Xendit SDK","level":"Debug"}]}
D/OkHttp  (20464): --> END POST (176-byte body)
I/Sentry  (20464): sentry-debug-meta.properties file was not found.
D/Sentry  (20464): SU isn't found on this Device.
W/pool-37-thread-(20464): type=1400 audit(0.0:439077): avc: denied { read } for name="version" dev="proc" ino=4026532087 scontext=u:r:untrusted_app:s0:c16,c258,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=id.iconix.mobile
D/OkHttp  (20464): --> POST https://logs.logdna.com/logs/ingest?hostname=xendit.co http/1.1
D/OkHttp  (20464): Content-Type: application/json;charset=UTF-8
D/OkHttp  (20464): Content-Length: 300
D/OkHttp  (20464): Authorization: Basic ZjMyNDg1NGZjYjJjYTNjMzk3YWEwNTM2ZTA1NTUwNzA6IA==
D/OkHttp  (20464): {"lines":[{"timestamp":1625192956,"line":"xnd_public_development_PYCFKOR10uCqkpQ6LOdPTDSTZdSioIV0wXLh\/Rhq\/WfS\/rCgDQF1 OS version: 4.19.127-g3ee621cec-dirty(eng.compil.20210507.155617)\n OS API Level: 30\n Device: 1904\n Model (and Product): vivo 1904 (1904)","file":"Xendit SDK","level":"Debug"}]}
D/OkHttp  (20464): --> END POST (300-byte body)
D/OkHttp  (20464): --> POST https://logs.logdna.com/logs/ingest?hostname=xendit.co http/1.1
D/OkHttp  (20464): Content-Type: application/json;charset=UTF-8
D/OkHttp  (20464): Content-Length: 173
D/OkHttp  (20464): Authorization: Basic ZjMyNDg1NGZjYjJjYTNjMzk3YWEwNTM2ZTA1NTUwNzA6IA==
D/OkHttp  (20464): {"lines":[{"timestamp":1625192956,"line":"xnd_public_development_PYCFKOR10uCqkpQ6LOdPTDSTZdSioIV0wXLh\/Rhq\/WfS\/rCgDQF1 Language: in","file":"Xendit SDK","level":"Debug"}]}
D/OkHttp  (20464): --> END POST (173-byte body)
D/OkHttp  (20464): --> POST https://logs.logdna.com/logs/ingest?hostname=xendit.co http/1.1
D/OkHttp  (20464): Content-Type: application/json;charset=UTF-8
D/OkHttp  (20464): Content-Length: 176
D/OkHttp  (20464): Authorization: Basic ZjMyNDg1NGZjYjJjYTNjMzk3YWEwNTM2ZTA1NTUwNzA6IA==
D/OkHttp  (20464): {"lines":[{"timestamp":1625192956,"line":"xnd_public_development_PYCFKOR10uCqkpQ6LOdPTDSTZdSioIV0wXLh\/Rhq\/WfS\/rCgDQF1 IP: 192.168.1.7","file":"Xendit SDK","level":"Debug"}]}
D/OkHttp  (20464): --> END POST (176-byte body)
D/OkHttp  (20464): --> POST https://logs.logdna.com/logs/ingest?hostname=xendit.co http/1.1
D/OkHttp  (20464): Content-Type: application/json;charset=UTF-8
D/OkHttp  (20464): Content-Length: 203
D/OkHttp  (20464): Authorization: Basic ZjMyNDg1NGZjYjJjYTNjMzk3YWEwNTM2ZTA1NTUwNzA6IA==
D/OkHttp  (20464): {"lines":[{"timestamp":1625192956,"line":"xnd_public_development_PYCFKOR10uCqkpQ6LOdPTDSTZdSioIV0wXLh\/Rhq\/WfS\/rCgDQF1 ADID: a20fb4d2-b83d-4692-9aec-74f4140a1a6b","file":"Xendit SDK","level":"Debug"}]}   
D/OkHttp  (20464): --> END POST (203-byte body)
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443 
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443 
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443 
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443 
D/OkHttp  (20464): <-- 403 Forbidden https://logs.logdna.com/logs/ingest?hostname=xendit.co (1781ms)
D/OkHttp  (20464): Server: restify
D/OkHttp  (20464): <-- 403 Forbidden https://logs.logdna.com/logs/ingest?hostname=xendit.co (1679ms)
D/OkHttp  (20464): <-- 403 Forbidden https://logs.logdna.com/logs/ingest?hostname=xendit.co (1796ms)
D/OkHttp  (20464): Server: restify
D/OkHttp  (20464): Server: restify
D/OkHttp  (20464): Server: Microsoft-IIS/8.0
D/OkHttp  (20464): Server: Microsoft-IIS/8.0
D/OkHttp  (20464): Content-Security-Policy: frame-ancestors 'none'
D/OkHttp  (20464): Content-Security-Policy: frame-ancestors 'none'
D/OkHttp  (20464): Server: Microsoft-IIS/8.0
D/OkHttp  (20464): Strict-Transport-Security: max-age=31536000; includeSubDomains
D/OkHttp  (20464): Content-Security-Policy: frame-ancestors 'none'
D/OkHttp  (20464): X-AspNetMvc-Version: 4.0
D/OkHttp  (20464): Strict-Transport-Security: max-age=31536000; includeSubDomains
D/OkHttp  (20464): X-AspNet-Version: 4.0.30319
D/OkHttp  (20464): X-AspNetMvc-Version: 4.0
D/OkHttp  (20464): X-Powered-By: ASP.NET
D/OkHttp  (20464): X-AspNet-Version: 4.0.30319
D/OkHttp  (20464): Content-Type: application/json
D/OkHttp  (20464): X-Powered-By: ASP.NET
D/OkHttp  (20464): Date: Fri, 02 Jul 2021 02:29:17 GMT
D/OkHttp  (20464): Content-Type: application/json
D/OkHttp  (20464): Connection: keep-alive
D/OkHttp  (20464): Date: Fri, 02 Jul 2021 02:29:17 GMT
D/OkHttp  (20464): Strict-Transport-Security: max-age=31536000; includeSubDomains
D/OkHttp  (20464): Connection: keep-alive
D/OkHttp  (20464): X-AspNetMvc-Version: 4.0
D/OkHttp  (20464): X-AspNet-Version: 4.0.30319
D/OkHttp  (20464): Keep-Alive: timeout=5
D/OkHttp  (20464): X-Powered-By: ASP.NET
D/OkHttp  (20464): Transfer-Encoding: chunked
D/OkHttp  (20464): Keep-Alive: timeout=5
D/OkHttp  (20464): Transfer-Encoding: chunked
D/OkHttp  (20464): Content-Type: application/json
D/OkHttp  (20464): Date: Fri, 02 Jul 2021 02:29:17 GMT
D/OkHttp  (20464): Connection: keep-alive
D/OkHttp  (20464): Keep-Alive: timeout=5
D/OkHttp  (20464): Transfer-Encoding: chunked
D/OkHttp  (20464): <-- 403 Forbidden https://logs.logdna.com/logs/ingest?hostname=xendit.co (1935ms)
D/OkHttp  (20464): Server: restify
D/OkHttp  (20464): Server: Microsoft-IIS/8.0
D/OkHttp  (20464): Content-Security-Policy: frame-ancestors 'none'
D/OkHttp  (20464): Strict-Transport-Security: max-age=31536000; includeSubDomains
D/OkHttp  (20464): X-AspNetMvc-Version: 4.0
D/OkHttp  (20464): X-AspNet-Version: 4.0.30319
D/OkHttp  (20464): X-Powered-By: ASP.NET
D/OkHttp  (20464): Content-Type: application/json
D/OkHttp  (20464): Date: Fri, 02 Jul 2021 02:29:18 GMT
D/OkHttp  (20464): Connection: keep-alive
D/OkHttp  (20464): Keep-Alive: timeout=5
D/OkHttp  (20464): Transfer-Encoding: chunked
D/OkHttp  (20464): <-- 403 Forbidden https://logs.logdna.com/logs/ingest?hostname=xendit.co (2427ms)
D/OkHttp  (20464): Server: restify
D/OkHttp  (20464): Server: Microsoft-IIS/8.0
D/OkHttp  (20464): Content-Security-Policy: frame-ancestors 'none'
D/OkHttp  (20464): Strict-Transport-Security: max-age=31536000; includeSubDomains
D/OkHttp  (20464): X-AspNetMvc-Version: 4.0
D/OkHttp  (20464): X-AspNet-Version: 4.0.30319
D/OkHttp  (20464): X-Powered-By: ASP.NET
D/OkHttp  (20464): Content-Type: application/json
D/OkHttp  (20464): Date: Fri, 02 Jul 2021 02:29:18 GMT
D/OkHttp  (20464): Connection: keep-alive
D/OkHttp  (20464): Keep-Alive: timeout=5
D/OkHttp  (20464): Transfer-Encoding: chunked
D/OkHttp  (20464): {"error":"Account inactive, please login to https://app.logdna.com first. Ingestion will resume within 30 minutes.","code":"NotAuthorized","status":"error"}
D/OkHttp  (20464): {"error":"Account inactive, please login to https://app.logdna.com first. Ingestion will resume within 30 minutes.","code":"NotAuthorized","status":"error"}
D/OkHttp  (20464): <-- END HTTP (156-byte body)
D/OkHttp  (20464): <-- END HTTP (156-byte body)
D/Logger  (20464): code: 403 success: false
D/Logger  (20464): code: 403 success: false
D/OkHttp  (20464): {"error":"Account inactive, please login to https://app.logdna.com first. Ingestion will resume within 30 minutes.","code":"NotAuthorized","status":"error"}
D/OkHttp  (20464): <-- END HTTP (156-byte body)
D/Logger  (20464): code: 403 success: false
D/OkHttp  (20464): {"error":"Account inactive, please login to https://app.logdna.com first. Ingestion will resume within 30 minutes.","code":"NotAuthorized","status":"error"}
D/OkHttp  (20464): <-- END HTTP (156-byte body)
D/Logger  (20464): code: 403 success: false
D/OkHttp  (20464): {"error":"Account inactive, please login to https://app.logdna.com first. Ingestion will resume within 30 minutes.","code":"NotAuthorized","status":"error"}
D/OkHttp  (20464): <-- END HTTP (156-byte body)
D/Logger  (20464): code: 403 success: false
D/Volley  (20464): [36322] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://api.xendit.co/v2/credit_card_tokens 0x9bd75db8 NORMAL 1> [lifetime=4203], [size=172], [rc=404], [retryCount=0]
E/Volley  (20464): [36322] BasicNetwork.performRequest: Unexpected response code 404 for https://api.xendit.co/v2/credit_card_tokens
D/OkHttp  (20464): --> POST https://logs.logdna.com/logs/ingest?hostname=xendit.co http/1.1
D/OkHttp  (20464): Content-Type: application/json;charset=UTF-8
D/OkHttp  (20464): Content-Length: 189
D/OkHttp  (20464): Authorization: Basic ZjMyNDg1NGZjYjJjYTNjMzk3YWEwNTM2ZTA1NTUwNzA6IA==
D/OkHttp  (20464): {"lines":[{"timestamp":1625192960,"line":"xnd_public_development_PYCFKOR10uCqkpQ6LOdPTDSTZdSioIV0wXLh\/Rhq\/WfS\/rCgDQF1 Tokenization Error: 404 null","file":"Xendit SDK","level":"Error"}]}
D/OkHttp  (20464): --> END POST (189-byte body)
D/AndroidRuntime(20464): Shutting down VM
E/AndroidRuntime(20464): FATAL EXCEPTION: main
E/AndroidRuntime(20464): Process: id.iconix.mobile, PID: 20464
E/AndroidRuntime(20464): java.lang.IllegalArgumentException: Unsupported value: com.xendit.Models.XenditError@b51a711
E/AndroidRuntime(20464):        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/AndroidRuntime(20464):        at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:75)
E/AndroidRuntime(20464):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
E/AndroidRuntime(20464):        at com.xendit.fxendit.FxenditPlugin$1.onError(FxenditPlugin.java:97)
E/AndroidRuntime(20464):        at com.xendit.Xendit$9.onFailure(Xendit.java:728)
E/AndroidRuntime(20464):        at com.xendit.network.NetworkHandler.deliverError(NetworkHandler.java:34)
E/AndroidRuntime(20464):        at com.xendit.network.NetworkHandler.handleError(NetworkHandler.java:28)
E/AndroidRuntime(20464):        at com.xendit.network.DefaultResponseHandler.onErrorResponse(DefaultResponseHandler.java:31)
E/AndroidRuntime(20464):        at com.android.volley.Request.deliverError(Request.java:617)
E/AndroidRuntime(20464):        at com.xendit.network.BaseRequest.deliverError(BaseRequest.java:156)
E/AndroidRuntime(20464):        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
E/AndroidRuntime(20464):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(20464):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20464):        at android.os.Looper.loop(Looper.java:239)
E/AndroidRuntime(20464):        at android.app.ActivityThread.main(ActivityThread.java:8179)
E/AndroidRuntime(20464):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20464):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
E/AndroidRuntime(20464):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
I/Sentry  (20464): Not possible to read external files directory
D/Linux   (20464): [Posix_connect Debug]Process id.iconix.mobile :443
I/Process (20464): Sending signal. PID: 20464 SIG: 9
Lost connection to device.

**Comment by salkuadrat** [comment]
Hi @ifin2000 

Coba pakai versi terbaru (0.0.3).
Dependencies untuk xendit sdk and cardinal mobile sdk udah diupdate ke versi terbaru di 0.0.3
